# -*- coding: utf-8 -*-
"""Tipos de variáveis para trabalhar com ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J98XxxsP45786MY8hLYgJohVUQ2MTtCA

# Tipos de **Variáveis**

## Inteiro (int)
O tipo inteiro é um tipo composto por caracteres numéricos (algarismos) inteiros.

É um tipo usado para um número que pode ser escrito sem um componente decimal, podendo ter ou não um sinal, isto é: ser positivo oo negativo.
"""

idade = 18
ano = 2002

print (type(idade))
print (type(ano))

"""## Ponto flutuante ou Decimal (float)

É um tipo composto por caracteres numéricos (algarismos) decimais.

O ponto flutuante é um tipo usado para números racionais (números que podem ser representados por uma fração) informalmente conhecido como "números quebrados".
"""

altura = 1.78
peso = 75.50

print (type(altura))
print (type(peso))

"""## Complexo (complex)

Tipo de dado usado para resolver números complexos.

Esse tipo normalmente é usado em cálculos geométricos e científicos.

Um tipo complexo possui duas partes: a parte **real** e a parte **imaginária**, sendo que a parte imaginária contém um **j** no sufixo.
"""

a = 5 + 2j
b = 20 - 8j

print (type(a))
print (type(b))

"""## String (str)

Conjunto de caracteres dispostos numa determinada ordem, geralmente utilizada para representar palavras, frases ou textos.
"""

nome = "Luiz"
profissao = "Analista de BI"

print (type(nome))
print (type(profissao))

"""## Boolean (bool)

Tipo de dado lógico que pode assumir apenas dois valores: verdadeiro ou falso.

Na lógica computacional, pode ser considerado como 0 e 1.
"""

fim_de_semana = True
feriado = False

print (type(fim_de_semana))
print (type(feriado))

