# -*- coding: utf-8 -*-
"""Estruturas condicionais em ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbmLGxjr9Dt9l2fgfRLnouumIAkNnuqO

# Estruturas Condicionais

## Estrutura Condicional Simples

```
if .....:
  .......
```
"""

soma = 3

if soma == 3:
  print("O valor é igual a 3!")

"""## Estruturas Condicionais Compostas



```
if ......:
  ........
else:
  ........
```

## Operações Lógicas

### Igualdade
"""

numero1 = 2
numero2 = 2

if numero1 == numero2:
  print("Os valores são iguais!")
else:
  print("Os valores são diferentes!")

"""### Diferença"""

numero1 = 1
numero2 = 2

if numero1 != numero2:
  print("Os valores são diferentes!")
else:
  print("Os valores são iguais!")

"""### Maior/menor que"""

numero1 = 1
numero2 = 2

if numero1 > numero2:
  print("O número1 é maior que o número2!")
else:
  print("O número2 é maior que o número1!")

numero1 = 1
numero2 = 2

if numero1 < numero2:
  print("O número1 é menor que o número2!")
else:
  print("O número2 é menor que o número1!")

"""Maior/menor igual a"""

numero1 = 3
numero2 = 3

if numero1 >= numero2:
  print("O número1 é maior ou igual que o número2!")
else:
  print("O número1 é menor que o número1!")

numero1 = 3
numero2 = 3

if numero1 <= numero2:
  print("O número1 é menor ou igual que o número1!")
else:
  print("O número1 é maior que o número2!")

"""## Estruturas Condicionais Aninhadas"""

soma = 1

if soma>0:
  print("Soma maior do que 0!")
elif soma == 0:
    print("Soma igual a 0!")
else:
    print("Soma menor do que 0!")