# -*- coding: utf-8 -*-
"""03-Estruturas de repetição utilizando For.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZWb9pUSj7uBDPKj1hMsC2OUYnk05YmG

# Estrutura de repetição com "for"
"""

lista = [1, 2, 3, 4, 5]

for item in lista:
  print(item)