# -*- coding: utf-8 -*-
"""04-Estruturas de repetição utilizando While.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjdzgO0RBH25qF2131klhtjS9nQdWNhH

# Estrutura de repetição com "while"
"""

contador = 0

while contador <= 10:
  print("Valor do contador é", contador)
  contador += 1